version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: taskmanager-api
    depends_on:
      - db
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=taskdb;Username=postgres;Password=123456
    ports:
      - "5000:8080"
volumes:
  pgdata: